### ISSUE TITLE
Debería llamarse TicketEvent 

### ISSUE THREAD

**Issue by enelramon** [Elpelfry/RegistroPrioridades#3]
https://github.com/Elpelfry/RegistroPrioridades/blob/85d973a0c291905308d857e1394e492e82e3b884/app/src/main/java/edu/ucne/registroprioridades/presentation/ticket/TicketUiState.kt#L3

**Comment by Elpelfry** [comment]
Gracias por la observacion

**Comment by Elpelfry** [comment]
Listo
